### ISSUE TITLE
Improve jump search

### ISSUE THREAD

**Issue by Zircoz** [Zircoz/Searching-Algos-in-Python#8]
The current jump search implementation returns the position of first occurrence of number in array. Alter it to return all occurrences.

**Comment by darshildave** [comment]
I have raised a PR https://github.com/Zircoz/Searching-Algos-in-Python/pull/9

**Comment by Zircoz** [comment]
Run a manual check for your code by searching 4 in [ 0, 1, 3, 4, 4, 5, 8, 13, 22, 24, 55, 59, 4, 122, 213, 422, 555 ]
